// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Satizen_Api.Datos;

#nullable disable

namespace Satizen_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Satizen_Api.Models.InstitucionModels", b =>
                {
                    b.Property<int>("idInstitucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idInstitucion"));

                    b.Property<string>("celularInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correoInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccionInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefonoInstitucion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idInstitucion");

                    b.ToTable("Institucion");

                    b.HasData(
                        new
                        {
                            idInstitucion = 1,
                            celularInstitucion = "26347859",
                            correoInstitucion = "santaclare@gmail.com",
                            direccionInstitucion = "calle pepe",
                            nombreInstitucion = "Santa Clare",
                            telefonoInstitucion = "5467389"
                        },
                        new
                        {
                            idInstitucion = 2,
                            celularInstitucion = "2634785967",
                            correoInstitucion = "santaclara@gmail.com",
                            direccionInstitucion = "calle pepi",
                            nombreInstitucion = "Santa Clara",
                            telefonoInstitucion = "54673897"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
